import java.lang.Exception

fun main(args: Array<String>) {
    try {





    } catch (e: Exception) {
        e.printStackTrace()
    }
}